name: diarios-bot
services:
  - name: diario-fetcher
    github:
      repo: yourusername/diarios-bot
      branch: main
    run_command: go run cmd/worker/main.go
    environment_slug: go
    instance_count: 1
    instance_size_slug: basic-xxs
    alert_policy:
      operator: GREATER_THAN
      value: 0
      window: 5m
      metric: cpu_utilization
    envs:
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        value: your-key
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        value: your-secret
      - key: DO_SPACES_ENDPOINT
        value: nyc3.digitaloceanspaces.com
      - key: DB_CONN_STRING
        value: postgres://...

jobs:
  - name: diario-cron
    kind: worker
    run_command: go run cmd/worker/main.go
    schedule: "0 6 * * *"  # Every day at 6AM UTC
