services:
  postgres:
    image: postgres:17
    container_name: radar-oficial-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radar-oficial
    ports:
      - "5432:5432"
    volumes:
      - radar-oficial:/var/lib/postgresql/data

volumes:
  radar-oficial:
