name: Radar-Oficial Crawler

on:
  schedule:
    - cron: "0 7-19 * * *"  # every hour between 7 AM and 7 PM (inclusive)
  workflow_dispatch:

jobs:
  call-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Reindex knowledge base
        run: |
          curl -s -f "https://radar-oficial-kfrag.ondigitalocean.app/reindex"
