name: Call External API on Schedule

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:       # optional: allows manual run

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Endpoint
        run: |
          curl "https://radar-oficial-kfrag.ondigitalocean.app/crawl?slug=governo-pi"
