name: Radar-Oficial Crawler

on:
  schedule:
    - cron: "0 7-19 * * *"  # every hour between 7 AM and 7 PM (inclusive)
  workflow_dispatch:       # optional: allows manual run

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Endpoint
        run: |
          curl "https://radar-oficial-kfrag.ondigitalocean.app/crawl?slug=governo-pi"
